### ISSUE TITLE
CSS en HTML y no en archivo aparte

### ISSUE THREAD

**Issue by Indavelopers** [HackLab-Almeria/programaespacialalmeriense.space#1]
Si quieres ayuda, le puedo echar un ojo y limpiar el código y arreglar un poco el CSS para hacerlo responsivo y demás.

Si quieres, métele las funcionalidades que quieras y cuando esté ya todo dejas un mensaje y le doy una vuelta a todo el código.

**Comment by olea** [comment]
No te preocupes. Juanjo ya tiene algo preparado para mandar a la chingada
este engendro.

2016-04-29 10:50 GMT+02:00 Indavelopers notifications@github.com:

> Si quieres ayuda, le puedo echar un ojo y limpiar el código y arreglar un
> poco el CSS para hacerlo responsivo y demás.
> 
> Si quieres, métele las funcionalidades que quieras y cuando esté ya todo
> dejas un mensaje y le doy una vuelta a todo el código.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/HackLab-Almeria/programaespacialalmeriense.space/issues/1

## 

Ismael Olea

http://olea.org/diario/
